### ISSUE TITLE
Iteration Plan for October 2022

### ISSUE THREAD

**Issue by rbosker** [six7/figma-tokens#1267]
### Dates
**Start iteration:** 21-09-2022
**End iteration:** 21-10-2022
**Beta testing from:** 14-10-2022
**Planned release:** 20-10-2022

### Sprint Goals
- Adding and improving token types
- Improve Onboarding flow
- Improve non-local styles handling with renaming/deleting/syncing styles
- Improve other Quality of Life issues

Legend of annotations:
Mark | Description
-- | --
🔺 | P0 - first to to be worked on
💪 | Stretch goal for this iteration
🕜 | In Progress
⛔ | Blocked
🤞 | To be released

### 🆕 New or improved tokens

- [x] [Add Paragraph Indent parameter to typography token](https://github.com/six7/figma-tokens/issues/735)
- [x] [Support multi-value radii and spacing tokens](https://github.com/six7/figma-tokens/issues/110)
- [x] [Font family fallback support](https://github.com/six7/figma-tokens/issues/818)
- [x] [Add support for Asset tokens](https://github.com/six7/figma-tokens/issues/1265)
- [ ] ~~[Add border token type](https://github.com/six7/figma-tokens/issues/1266)~~
- [ ] ~~💪 [Introduce color modifiers](https://github.com/six7/figma-tokens/issues/1166)~~
- [ ] ~~💪 [Introduce dimension type](https://github.com/six7/figma-tokens/issues/1201)~~
- [ ] ~~[Box Shadow token alias mode should support multiple stacked shadows.](https://github.com/six7/figma-tokens/issues/706)~~
- [ ] ~~💪 [Custom rem configuration support](https://github.com/six7/figma-tokens/issues/401)~~
- [ ] ~~[Introduce duration tokens](https://github.com/six7/figma-tokens/issues/299)~~
- [ ] ~~[Ability to add Line Height token in rem units](https://github.com/six7/figma-tokens/issues/1045)~~
- [ ] ~~[Introduce CubicBezier Token](https://github.com/six7/figma-tokens/issues/1295)~~

### 🤖 token-transformer
- [ ] ~~[token-transformer merges tokens before deciding what set to exclude](https://github.com/six7/figma-tokens/issues/1182)~~

### 🤝 Onboarding
- [x] [Introduce Onboarding modal flow](https://github.com/six7/figma-tokens/issues/1200)
- [x] [Introduce new Start screen with helpful links](https://github.com/six7/figma-tokens/issues/1261)
- [ ] [Introduce in-product explainers](https://github.com/six7/figma-tokens/issues/1262)
- [ ] [Add a way to reset Onboarding](https://github.com/six7/figma-tokens/issues/1263)

### 🧑‍🎨 Non-local styles improvements
- [x] [When deleting a token, ask to delete any local styles](https://github.com/six7/figma-tokens/issues/1195)
- [x] [When renaming a token, ask to rename any local styles (in addition to the Remap tokens functionality we have)](https://github.com/six7/figma-tokens/issues/1194)
- [x] [In the Styles Actions, add a new "Sync styles" option which renames Styles according to their connected tokens (via Themes), deletes any styles that are not referenced, and creates new styles that do not exist yet](https://github.com/six7/figma-tokens/issues/1196)

### 😊 QoL
- [x] 🕜 [Changes to License key display](https://github.com/six7/figma-tokens/issues/1293)
- [ ] ~~💪 [Documentation Indicator Ring](https://github.com/six7/figma-tokens/issues/873)~~
- [ ] ~~💪 [Refactor how we show Sync/Settings](https://github.com/six7/figma-tokens/issues/1264)~~

### 🐛 Bugs
- [x] [Pro feature "Create new branch from" UI issue](https://github.com/six7/figma-tokens/issues/1184)
- [x] Added to Iteration: [Tokens not applying](https://github.com/six7/figma-tokens/issues/1316)
- [x] Added to Iteration: [When you copy a component that contains text, the applied tokens are undifined](https://github.com/six7/figma-tokens/issues/1313)

### 🪵 Logging
- [ ] ~~[Create Sentry exception when we fail to fetch](https://github.com/six7/figma-tokens/issues/1227)~~

### 🦨 Tech debt
- [ ] ~~[Refactor the TokenPicker component](https://github.com/six7/figma-tokens/issues/1203)~~
