### ISSUE TITLE
[Tracking]: Box Shadow improvements

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#281]
Box Shadows aren't properly supported yet, we should change that.

A couple of issue that are open:

- [ ] https://github.com/six7/figma-tokens/issues/163
- [x] https://github.com/six7/figma-tokens/issues/174
- [x] https://github.com/six7/figma-tokens/issues/234
- [x] https://github.com/six7/figma-tokens/issues/312

Currently we store box shadows as an object:
```
"boxShadow": {
    "dark": {
      "value": {
        "x": 5,
        "y": 5,
        "spread": 3,
        "color": "rgba(0, 0, 0, 0.5)",
        "blur": 5
      },
      "type": "boxShadow"
    }
  },
```

This doesn't really allow us to do something like multiple shadows.

Instead, I would propose to create boxShadows with an array syntax: `[5px 5px 5px 3px rgba(0, 0, 0, 0.5), 5px 5px 5px 3px rgba(0, 0, 0, 0.5)]` which would allow us to have multiple shadows. We could still pick up the values in the UI and possibly provide a nicer experience.

Also, this should allow us to import and export shadow styles more easily.

**Comment by six7** [comment]
I've been experimenting with this and got a basic version working with an array json.

I'll next tackle the UI.  What do you think of something like this? Doing what Figma does won't be possible as token value is still important and having 2 columns just doesn't give us the space.

![image](https://user-images.githubusercontent.com/4548309/140607331-d440281f-d79b-40f5-bd7f-efa63157a700.png)

**Comment by lukasoppermann** [comment]
This looks perfect. 😍

The color could also be RGB or hex8 to include opacity, correct?

**Comment by six7** [comment]
Yes, exactly! It would allow you to insert rgb(a), hex(8) or hsl(a)

**Comment by six7** [comment]
Closing this as it was shipped
