### ISSUE TITLE
Refactor files that contain too much logic which make it hard to test

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#2944]
Refactor files that contain too much logic which make it hard to test. E.g. `tokenState`, `useTokens`. We should optimize similar to how we did it in tokens-studio/figma-plugin#2704

```[tasklist]
### Tasks
- [ ] Investigate if we can automatically scan codebase for complex functions to identify the biggest problems
- [ ] Obtain list of most complex files. Target top (3 | 5)
- [ ] Create invididual plans to refactor each
```
