### ISSUE TITLE
[Tracking]: GitHub sync optimizations

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#310]
Collecting feedback in this issue to tackle optimizing the GitHub sync later on:

- [x] https://github.com/six7/figma-tokens/issues/321
- [x] https://github.com/six7/figma-tokens/issues/319
- [x] https://github.com/six7/figma-tokens/issues/327
- [x] #341
- [ ] #342
- [ ] #353
- [x] https://github.com/six7/figma-tokens/issues/315
- [x] https://github.com/six7/figma-tokens/issues/340
- [ ] https://github.com/six7/figma-tokens/issues/380
- [ ] https://github.com/six7/figma-tokens/issues/387
