### ISSUE TITLE
[Tracking]: Gradient fixes

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#354]
Gradients currently don't have the best support:

- [x] https://github.com/six7/figma-tokens/issues/286
- [x] https://github.com/six7/figma-tokens/issues/156
- [x] https://github.com/six7/figma-tokens/issues/326

**Comment by six7** [comment]
Closing this epic as gradient support has been shipped.
