### ISSUE TITLE
[Tracking]: Multi-layer inspector

### ISSUE THREAD

**Issue by six7** [six7/figma-tokens#355]
Let's use this issue to write up our plan for a multi-layer Token Inspector

Wishlist:
- Allow to batch reassign tokens
- Allow to batch remove tokens
- See missing token links

# Todo
- [x] https://github.com/six7/figma-tokens/issues/165
- [x] https://github.com/six7/figma-tokens/issues/247
- [x] Allow users to batch reassign tokens
- [x] Allow users to see missing token links
- [x] Allow users to remove a specific token from a single layer or multiple layers
- [x] Allow users to remove all tokens from a single layer or multiple layers
- [ ] Allow users to swap a specific token on a specific layer with another one / on multiple layers

**Comment by ZachShea** [comment]
Chiming in on this one, I'd love to batch remove tokens from layers

**Comment by benhami1ton** [comment]
Would multi-layers apply to nested layers within a component? I'm finding myself working with nested components coming from other libraries, and it'd be helpful to see the tokens applied to layers within the one I've selected, maybe grouped by the layer they're applied to. But I could also see how that might get redundant if the goal is to select multiple layers and batch view/apply/remove tokens to all of them.

**Comment by rbascue** [comment]
Will this apply to the documentation tokens? I noticed if I change a token parent name (i.e. grey -> neutral), the linked text layers don't update. It successfully updates the text layers linked to the raw values, though.

**Comment by six7** [comment]
> Will this apply to the documentation tokens? I noticed if I change a token parent name (i.e. grey -> neutral), the linked text layers don't update. It successfully updates the text layers linked to the raw values, though.

You'll be able to batch-change tokens with this method, meaning after you renamed something you could select all that contain the old token and choose a new one instead. It won't automatically do this for you, but that's a feature on its own.

**Comment by six7** [comment]
> Would multi-layers apply to nested layers within a component? I'm finding myself working with nested components coming from other libraries, and it'd be helpful to see the tokens applied to layers within the one I've selected, maybe grouped by the layer they're applied to. But I could also see how that might get redundant if the goal is to select multiple layers and batch view/apply/remove tokens to all of them.

Yes! It will have a way to deep-select layers, not just the currently selected one. This will come with a small performance hit (as it has to scan all layers and all of its children), but will do what you described. You'll however only be able to see what tokens are applied, not to which layer (you'd be able to select those layers though, so you could further specify).

**Comment by six7** [comment]
I'll be closing this issue and collecting any feedback in a new tracking issue now that Multi inspect is released.
